version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: afara_ninge_linistit
      MYSQL_DATABASE: drones
    ports:
      - "3306:3306"
